### ISSUE TITLE
The mod failed to load

### ISSUE THREAD

**Issue by aaa-chinese** [Stormride-R/Cruxscape-Takeover#1]
When I tried to load the mod into the game, an error occurred and the mod failed to load.
- Using game version: 146 release
- latest log:
```
[E] java.io.IOException: java.lang.ClassNotFoundException: cruxahh.cruxahh
	at mindustry.mod.Mods.importMod(Mods.java:130)
	at mindustry.ui.dialogs.ModsDialog.lambda$setup$18(ModsDialog.java:174)
	at mindustry.ui.dialogs.FileChooser.lambda$setupWidgets$3(FileChooser.java:74)
	at arc.scene.Element.lambda$clicked$2(Element.java:913)
	at arc.scene.Element$4.clicked(Element.java:922)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:31)
	at arc.scene.Scene.touchUp(Scene.java:370)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:136)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:181)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:189)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: java.lang.ClassNotFoundException: cruxahh.cruxahh
	at mindustry.mod.ModClassLoader.findClass(ModClassLoader.java:27)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at mindustry.core.Platform$1.loadClass(Platform.java:37)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at mindustry.mod.ModClassLoader.findClass(ModClassLoader.java:38)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at mindustry.core.Platform$1.loadClass(Platform.java:37)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at mindustry.mod.Mods.loadMod(Mods.java:958)
	at mindustry.mod.Mods.importMod(Mods.java:111)
	... 13 more
```

**Comment by aaa-chinese** [comment]
also the mod version is the latest release, "0025 the beta test".

**Comment by Stormride-R** [comment]
try 0026,
iceboundtributary map was saved in BE_build so it went wrong in 0025

**Comment by aaa-chinese** [comment]
I think you need to actually build the mod..
It's a jar mod, so your release should have a .jar in it.

**Comment by Stormride-R** [comment]
how do i
